apiVersion: v1
kind: Pod
metadata:
  name: dstools
  labels:
    app: rstudio
spec:
  containers:
    - name: rstudio
      image: anarinsk/rstudio-m1-korfont
      env:
        - name: PASSWORD
          value: "1022"
        - name: UMASK
          value: "000"
        - name: ROOT 
          value: "true" 
      ports:
        containerPort: 8787
      volumeMounts:
        - name: anari-github
          mountPath: /home/rstudio/anari-github
  #        
  restartPolicy: "OnFailure"
  #
  volumes:
    - name: anari-github
      hostPath: 
        path: /Users/anari/Documents/GitHub # macos 