apiVersion: v1
kind: PersistentVolume
metadata:
  name: anari-github
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /Users/anari/Documents/GitHub # macos 
    type: Directory


## Rescue command 

#kubectl create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ --docker-username=anarinsk --docker-password=sksms72sustod --docker-email=anarinsk@gmail.com
#kubectl patch pv NAME-OF-PV -p '{"metadata":{"finalizers": null}}'