apiVersion: v1
kind: PersistentVolume
metadata:
  name: dockerfile
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /Users/anari/Documents/GitHub/setup_k8s/kaniko # replace with local directory, such as "/home/<user-name>/kaniko"
#kubectl create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ --docker-username=anarinsk --docker-password=sksms72sustod --docker-email=anarinsk@gmail.com

#kubectl get pv | tail -n+2 | awk '{print $1}' | xargs -I{} kubectl patch pv {} -p '{"metadata":{"finalizers": null}}'