# All are obsolete 
#FROM twaddlac/datascience-notebook-m1-compatible
#FROM achirosca/datascience-notebook:latest
#FROM jpdolz/datascience-notebook:latest -> Julia is excluded 
FROM jupyter/datascience-notebook:aarch64-latest


# Declare root as user 
USER root

# Update Ubuntu / Install Nanum for Korean Font
RUN sed -i 's|http://ports.ubuntu.com/ubuntu-ports|http://ftp.lanet.kr/ubuntu-ports|g' /etc/apt/sources.list
# sed -i 's/security.ubuntu.com/mirror.kakao.com/g' /etc/apt/sources.list && \
RUN apt-get update && \
    apt-get -y upgrade && \
    sudo apt-get install -y fonts-naver-d2coding && \
    #apt-get install -y fonts-nanum* && \
    pip3 install --upgrade pip && \
    apt-get install fontconfig -y && \
    fc-cache -f -v && \
    rm -rf /home/jovyan/.cache/matplotlib